### ISSUE TITLE
Compatibility with ProMicro or Teensy LC

### ISSUE THREAD

**Issue by 0mars** [eclab/gizmo#3]
Is gizmo compatible or tested on either chips ? I have a teensy already was wondering if it can work
**Teensy LC Specs**
https://www.pjrc.com/teensy/teensyLC.html

**Pro Micro Specs **
Specifications |  
-- | --
Size | 34mm x 18mm x 7mm (with header pins installed)
Processor | 16 Mhz ATmega32U4
Input Voltage | 5-9V Recommended.Can be powered via USB
Digital Input/Outputs | 14 digital I/O pins (2 used for TX/RX)6 PWM capable (D3, D5, D6, D9, D10, D11)
Analog Inputs | 4 x 10-bit resolution input.
Flash Memory | 32Kb (4Kb used by bootloader)

**Comment by eclab** [comment]
Gizmo has only been tested on the Uno and Mega, no other platforms.  So I can't say what it'd take to get it working on others.

**Comment by Beltshassar** [comment]
I've had a go with esp8266 quite recently, but unfortunately I didn't have any luck. Apart from the missing analog i/o, I hoped to run a fullblown Gizmo on a microscopic platform with a lot of storage -relatively. But after messing around with the code I got stuck at the EEPROM r/w which didn't seem to work with the esp. Now I'm trying my luck with a Arduino Due and a diy midi-hat.
