### ISSUE TITLE
'class TwoWire' has no member named 'endTransmissionNonblocking'; did you mean 'endTransmission'?

### ISSUE THREAD

**Issue by Andrjazz** [eclab/gizmo#4]
Hello. Help please, when I upload sketch in arduino IDE wrote error 
'class TwoWire' has no member named 'endTransmissionNonblocking'; did you mean 'endTransmission'?

I installed all libraries in my PC

Thanks

**Comment by eclab** [comment]
See the instructions in the manual.

**Comment by Andrjazz** [comment]
> See the instructions in the manual.
> […](#)
> On Dec 21, 2020, at 5:48 AM, Andrjazz ***@***.***> wrote: Hello. Help please, when I upload sketch in arduino IDE wrote error 'class TwoWire' has no member named 'endTransmissionNonblocking'; did you mean 'endTransmission'? I installed all libraries in my PC Thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you, read manual and fix wire.h, and sketch upload. Thank you

**Comment by Andrjazz** [comment]
Оne more question. Can I use MAX7219 for  16x8 LED matrix, instead ht16k33?

**Comment by eclab** [comment]
I cannot answer this question, as I know no nothing about this LED, except to say that you'll probably have to modify the LEDDisplay.cpp file.
