### ISSUE TITLE
How to modify wire.h and wire.cpp

### ISSUE THREAD

**Issue by Inductor-Hub** [eclab/gizmo#5]
Hi Eclab,

I have difficulties in modifying wire.h and wire.cpp according to the manual. It seems that these files don't have multiple places according the the mac finder. BTW I do Arduino coding, but I am not much an experienced programmer.
 I have no idea where exactly to insert the lines. Is it perhaps needed to add the code in wire.h in several "public" places? What is the best place in wire.cpp

I attach the files I modified so far.

Thanks a lot for your support.
Jens
PS the error message is 
Arduino: 1.8.13 (Mac OS X), Board: "Arduino Yún"

[wire_files.zip](https://github.com/eclab/gizmo/files/6091584/wire_files.zip)

sketch/LEDDisplay.cpp: In function 'void sendMatrix(unsigned char*, unsigned char*)':
LEDDisplay.cpp:1259:10: error: 'class TwoWire' has no member named 'endTransmissionNonblocking'; did you mean 'endTransmission'?
     Wire.endTransmissionNonblocking();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          endTransmission
sketch/LEDDisplay.cpp: In function 'void setScreenBrightness(uint8_t)':
LEDDisplay.cpp:2286:10: error: 'class TwoWire' has no member named 'endTransmissionNonblocking'; did you mean 'endTransmission'?
     Wire.endTransmissionNonblocking();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
          endTransmission
Mehrere Bibliotheken wurden für "MIDI.h" gefunden
 Benutzt: /Users/michaela/Documents/JensWelt/Arduino/libraries/MIDI
 Nicht benutzt: /Users/michaela/Documents/JensWelt/Arduino/libraries/MIDI_Library
exit status 1
'class TwoWire' has no member named 'endTransmissionNonblocking'; did you mean 'endTransmission'?
/Users/michaela/Library/Arduino15/packages/ATTinyCore/hardware/avr/1.3.3/libraries/Wire/src/Wire.cpp

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

**Comment by eclab** [comment]
I have not checked with the most recent versions of the Arduino IDE, but at least as of last time I was examining things, yes, on the Mac there were *TWO* copies of each of these files which must be BOTH modified. I don't know if this is still the case.  On cursory glance your code appears to be correct.

Sean

**Comment by Inductor-Hub** [comment]
Dear Sean,

many thanks for your fast reply. In fact, you were fully right. I found finally the second locations of the files and adjusted them. Now it compiles (after finding out to specify the correct board...) without problems.

Best regards
Jens
