### ISSUE TITLE
Top-level Arpeggiator menu

### ISSUE THREAD

**Issue by Inductor-Hub** [eclab/gizmo#6]
Hi Sean,

my Gizmo is now compiled and runs on a Mega with the Sparkfunh shield. There seems to be full functionality ad its just great. However, I notice a strange behaviour in the top-level Arpeggiator menu. I can't reach the final CREATE item. I can switch with Pot1 through the Arpeggiator presets until user preset 8, sometimes even to user preset 9, but then it seems to reboot if I turn the pot futher, thus I can't reach the CREATE option to choose. I do have white display, which causes some noise on the 5V pin, causing some toggling in the display messages, but even with a RC Lowpass stable 5V I do not succeed. 
Do I have to adjust some settings in the files and recompile? What would be the best starting point?

Best regards
Jens

**Comment by eclab** [comment]
Hi Jens.  A day or so ago I identified a stupid, stupid bug I had introduced which should cause this.   I have just committed a simple bug for it: in Utility.h, MAX_MENU_ITEMS should be 18, not 17.   Try pulling again and see if it still has the problem.  

Sean

**Comment by Inductor-Hub** [comment]
Hi Sean,

now it works! Thanks for your help. Would have been impossible for me to find that.
Jens
