### ISSUE TITLE
Use a 16x2 LCD Display

### ISSUE THREAD

**Issue by TygerTung** [eclab/gizmo#9]
Would it be possible to use one of these old school style 1602 16x2 LCD displays? They are cheaper and maybe they would be able to display the text on the screen without having to have it scroll across?

https://www.aliexpress.com/item/32845856464.html?spm=a2g0o.productlist.0.0.10253440K0aJdv&algo_pvid=3a7ecb7f-ef52-4e48-9ff9-c63817214f68&algo_exp_id=3a7ecb7f-ef52-4e48-9ff9-c63817214f68-0&pdp_ext_f=%7B%22sku_id%22%3A%2265129311451%22%7D&pdp_pi=-1%3B2.03%3B-1%3B-1%40salePrice%3BNZD%3Bsearch-mainSearch

I don't really know anything about computer programming, but I am keen to make one of these MIDI arpeggiators. I have ordered a midi shield and have a mega 2560 already. Just wondering if I can use the cheaper display.

Cheers,
Sam

**Comment by SeanLuke** [comment]
Gizmo won't work with these screens, not with a massive amount of rewriting.  Gizmo doesn't just use its pixels to draw letters: it also uses them to display grids of notes for most of its applications.

**Comment by eclab** [comment]
Gizmo doesn't just scroll text -- it uses the individual pixels as a grid for the arpeggiator, recorder, step sequencer, and drum sequencer apps.
